/* Modelagem Básica - 

ENTIDADE = TABELA
CAMPOS = ATRIBUTOS */

CLIENTE

NOME - CARACTERES(30)
CPF - NUMERICO (11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - AD (ADM DE DADOS) */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FISICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FISICA */

/* CRIANDO O BANCO DE DADOS*/

CREATE DATABASE EXEMPLO;

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA CLIENTES */

CREATE TABLE CLIENTE( 
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDEREÇO VARCHAR(100)
	
);

/*VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

USE EXEMPLO;
SHOW TABLES;

USE PROJETO;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE; 

/* SINTAXE BASICA DE INSERÇÃO - INSERTO INTO TABELA... */
 
 /* FORMA 01 - OMITINDO AS COLUNAS*/ 
INSERT INTO CLIENTE VALUES ('JOA0', 'M', 'JOAO@GMAIL.COM', 988638723, '22923110', ' MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');
 
INSERT INTO CLIENTE VALUES('CELIA', 'F', 'CELIA@GMAIL.COM', 54141231, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('JORGE', 'M', NULL, 39281739, '34123182', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
						  
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999999);

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222222);

/* COMANDO SELECT
seleção projeção e junção

SELECT É UMA PROJEÇÃO
 */

 SELECT NOW() AS DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;
 
 SELECT 'FELIPE MAFRA';
 
 SELECT 'BANCO DE DADOS';
 
 /* ALIAS DE COLUNAS*/
 
 SELECT NOME AS CLIENTE,SEXO, EMAIL FROM CLIENTE;
  
 SELECT NOME, SEXO, EMAIL FROM CLIENTE;
 
 SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
 
 SELECT EMAIL, SEXO,ENDERECO, NOME FROM CLIENTE;
 
 SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;
 
 /* TABELA ERRADA - NAO DIGITE DIRETAMENTE NO BANCO*/
 CREATE TABLE CLIENTE( 
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDEREÇO VARCHAR(100),
	
);

/* APENAS PARA FINS ACADEMICOS*/
 SELECT * FROM CLIENTE;

/*FILTRANDO DADOS COM WHERE E LIKE */
 
SELECT NOME, TELEFONE FROM CLIENTE;
 
/*FILTRANDO*/

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE 
WHERE SEXO = 'F';

/* UTILIZANDO O LIKE*/
SELECT NOME, SEXO FROM CLIENTE 
WHERE ENDERECO LIKE'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE'%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE'%CENTRO%';

/*  EXERCICIO DE REVISAO */
CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS (
 LIVRO VARCHAR(100),
 AUTOR VARCHAR(100),
 SEXO CHAR(1),
 PAGINAS INT (5),
 EDITORA VARCHAR(30),
 VALOR FLOAT(10,2),
 UF CHAR(2),
 PUBLICACAO int(4)
);


INSERT INTO LIVROS VALUES ('Cavaleiro Real' , 'Ana Claudia','F', 465, 'Atlas', 49.9, 'RJ',2009);

INSERT INTO LIVROS VALUES ('SQL para leigos', 'João Nunes','M', 450,'Addison', 98, 'SP', 2018 );	

INSERT INTO LIVROS VALUES('Receitas Caseiras', 'Celia Tavares', 'F', 210, 'ATLAS', 45, 'RJ', 2008);		

INSERT INTO LIVROS VALUES('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', 2018);
							
INSERT INTO LIVROS VALUES('Habitos Saudáveis','Eduardo Santos', 'M',630, 'Beta',150.98,	'RJ', 2019);

INSERT INTO LIVROS VALUES('A Casa Marrom', 'Hermes Macedo','M',250,	'Bubba', 60,'MG',2016);		

INSERT INTO LIVROS VALUES('Estacio Querido',	'Geraldo Francisco',	'M',	310,	'Insignia',	100,	'ES',	2015);	

INSERT INTO LIVROS VALUES('Pra sempre amigas',	'Leda Silva',	'F',	510,	'Insignia',	78.98,	'ES',	2011);

INSERT INTO LIVROS VALUES('Copas Inesqueciveis','Marco Alcantara',	'M',	200,	'Larson',	130.98,	'RS',	2018);

INSERT INTO LIVROS VALUES( 'O poder da mente',	'Clara Mafra',	'F',	120,	'Continental'	,56.58,	'SP',	2017);


/* 1 – Trazer todos os dados */
SELECT * FROM LIVROS;
 
/*2 – Trazer o nome do livro e o nome da editora */
SELECT LIVRO, EDITORA
 FROM LIVROS;
 
/*3 – Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino. */
SELECT AUTOR, LIVRO, UF  FROM LIVROS
WHERE SEXO ='M';

/* 4 - Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino.*/
SELECT AUTOR, LIVRO, PAGINAS  FROM LIVROS
WHERE SEXO ='F';

/* 5 – Trazer os valores dos livros das editoras de São Paulo.*/
SELECT VALOR FROM LIVROS 
WHERE UF = 'SP';

/* 6 – Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro (Questão Desafio).*/

SELECT AUTOR, SEXO, UF
FROM LIVROS
WHERE 
SEXO = 'M' AND (UF = 'SP' OR UF = 'RJ');

SELECT AUTOR, SEXO, UF
FROM LIVROS
WHERE SEXO = 'M'
AND UF = 'SP'
AND paginas > 100;

/* OR - OU */

SHOW DATABASES;

USE PROJETO;

SELECT * FROM CLIENTE;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO  FROM CLIENTE
WHERE
SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

/* AND - E */

SELECT NOME, SEXO, ENDERECO  FROM CLIENTE
WHERE 
SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

/* COUNT(*), GROUP BY, PERFOMANCE COM OPERADORES LÓGICOS */

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) AS "QUANTIDADE DE REGISTROS DA TAB. CLIENTE" FROM CLIENTE;

/* OPERADOR GROUP BY*/

SELECT SEXO, COUNT(*)
FROM CLIENTE;

SELECT * FROM CLIENTE;

SELECT SEXO, COUNT(*)
FROM CLIENTE 
GROUP BY SEXO;

/* PERFOMANCE EM OPERADORES LOGICOS */

/* 1 MILHAO DE REGISTROS

PARA CONTAR
SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT CIDADE, COUNT(*) FROM CLIENTE
GROUP BY CIDADE;

CONDICAO
SEXO = F
CIDADE = RIO DE JANEIRO

SITUACAO - TRATANDO COM OU / OR
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F'
OR CIDADE = 'RIO DE JANEIRO';

SITUACAO - TRATANDO COM E / AND
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE CIDADE = 'RIO DE JANEIRO'
AND SEXO = 'F';
*/


